export const LEADS = [
    {
      id: 1,
      title: "Software Engineer",
      company: "Tech Corp",
      company_id: 101,
      location: "New York, NY",
      salary: 120000,
      description: "Develop and maintain software applications.",
      jobPostingUrl: "https://example.com/job/1",
      jobPostingDate: "2025-01-11",
      status: "Applied",
    },
    {
      id: 2,
      title: "Frontend Developer",
      company: "Web Solutions",
      company_id: 102,
      location: "San Francisco, CA",
      salary: 115000,
      description: "Build and optimize user-facing features using React.js.",
      jobPostingUrl: "https://example.com/job/2",
      jobPostingDate: "2025-01-10",
      status: "Interviewing",
    },
    {
      id: 3,
      title: "Backend Developer",
      company: "DataFlow Inc.",
      company_id: 103,
      location: "Chicago, IL",
      salary: 130000,
      description: "Design and develop server-side applications and databases.",
      jobPostingUrl: "https://example.com/job/3",
      jobPostingDate: "2025-01-12",
      status: "Interviewing",
    },
    {
      id: 4,
      title: "Product Manager",
      company: "Tech Innovations",
      company_id: 104,
      location: "Austin, TX",
      salary: 140000,
      description: "Lead product development from ideation to launch.",
      jobPostingUrl: "https://example.com/job/4",
      jobPostingDate: "2025-01-09",
      status: "Applied",
    },
    {
      id: 5,
      title: "Data Scientist",
      company: "AI Solutions",
      company_id: 105,
      location: "Boston, MA",
      salary: 125000,
      description: "Analyze large data sets to extract actionable insights.",
      jobPostingUrl: "https://example.com/job/5",
      jobPostingDate: "2025-01-08",
      status: "Interviewing",
    },
    {
      id: 6,
      title: "DevOps Engineer",
      company: "CloudTech",
      company_id: 106,
      location: "Seattle, WA",
      salary: 110000,
      description: "Implement and manage CI/CD pipelines for cloud infrastructure.",
      jobPostingUrl: "https://example.com/job/6",
      jobPostingDate: "2025-01-07",
      status: "Not Selected",
    },
    {
      id: 7,
      title: "UX Designer",
      company: "Creative Minds",
      company_id: 107,
      location: "Los Angeles, CA",
      salary: 105000,
      description: "Design user-friendly interfaces and improve user experience.",
      jobPostingUrl: "https://example.com/job/7",
      jobPostingDate: "2025-01-06",
      status: "Applied",
    },
    {
      id: 8,
      title: "Full Stack Developer",
      company: "Tech Enterprises",
      company_id: 108,
      location: "Denver, CO",
      salary: 125000,
      description: "Work on both front-end and back-end development tasks.",
      jobPostingUrl: "https://example.com/job/8",
      jobPostingDate: "2025-01-05",
      status: "Applied",
    },
    {
      id: 9,
      title: "Security Engineer",
      company: "CyberSec Solutions",
      company_id: 109,
      location: "Washington, DC",
      salary: 135000,
      description: "Monitor and protect the company's infrastructure from cyber threats.",
      jobPostingUrl: "https://example.com/job/9",
      jobPostingDate: "2025-01-04",
      status: "Applied",
    },
    {
      id: 10,
      title: "Database Administrator",
      company: "DBTech",
      company_id: 110,
      location: "Miami, FL",
      salary: 100000,
      description: "Manage and optimize databases for performance and security.",
      jobPostingUrl: "https://example.com/job/10",
      jobPostingDate: "2025-01-03",
      status: "Interviewing",
    },
    {
      id: 11,
      title: "Mobile Developer",
      company: "AppWorks",
      company_id: 111,
      location: "Chicago, IL",
      salary: 110000,
      description: "Develop and maintain iOS and Android applications.",
      jobPostingUrl: "https://example.com/job/11",
      jobPostingDate: "2025-01-02",
      status: "Applied",
    },
    {
      id: 12,
      title: "System Administrator",
      company: "TechOps",
      company_id: 112,
      location: "Austin, TX",
      salary: 95000,
      description: "Ensure smooth operation of company networks and systems.",
      jobPostingUrl: "https://example.com/job/12",
      jobPostingDate: "2025-01-01",
      status: "Applied",
    },
    {
      id: 13,
      title: "Cloud Engineer",
      company: "Nimbus Technologies",
      company_id: 113,
      location: "San Francisco, CA",
      salary: 125000,
      description: "Build and maintain cloud infrastructures for clients.",
      jobPostingUrl: "https://example.com/job/13",
      jobPostingDate: "2025-01-15",
      status: "Interviewing",
    },
    {
      id: 14,
      title: "Marketing Specialist",
      company: "GrowthHub",
      company_id: 114,
      location: "Los Angeles, CA",
      salary: 90000,
      description: "Develop marketing strategies to increase brand awareness.",
      jobPostingUrl: "https://example.com/job/14",
      jobPostingDate: "2025-01-13",
      status: "Applied",
    },
    {
      id: 15,
      title: "Data Engineer",
      company: "BigData Co.",
      company_id: 115,
      location: "New York, NY",
      salary: 115000,
      description: "Build and optimize data pipelines for large-scale data analysis.",
      jobPostingUrl: "https://example.com/job/15",
      jobPostingDate: "2025-01-14",
      status: "Not Selected",
    },
    {
      id: 16,
      title: "Software Architect",
      company: "Innovative Tech",
      company_id: 116,
      location: "Seattle, WA",
      salary: 160000,
      description: "Design the software architecture for large-scale systems.",
      jobPostingUrl: "https://example.com/job/16",
      jobPostingDate: "2025-01-16",
      status: "Applied",
    },
    {
      id: 17,
      title: "Business Analyst",
      company: "Enterprise Solutions",
      company_id: 117,
      location: "Denver, CO",
      salary: 105000,
      description: "Analyze business processes and provide recommendations.",
      jobPostingUrl: "https://example.com/job/17",
      jobPostingDate: "2025-01-17",
      status: "Applied",
    },
    {
      id: 18,
      title: "Software Tester",
      company: "QualitySoft",
      company_id: 118,
      location: "Miami, FL",
      salary: 85000,
      description: "Perform software testing and ensure product quality.",
      jobPostingUrl: "https://example.com/job/18",
      jobPostingDate: "2025-01-18",
      status: "Interviewing",
    },
    {
      id: 19,
      title: "Game Developer",
      company: "PixelGames",
      company_id: 119,
      location: "San Diego, CA",
      salary: 120000,
      description: "Design and develop interactive games for multiple platforms.",
      jobPostingUrl: "https://example.com/job/19",
      jobPostingDate: "2025-01-19",
      status: "Offered",
    },
    {
      id: 20,
      title: "AI Researcher",
      company: "FutureAI",
      company_id: 120,
      location: "Boston, MA",
      salary: 145000,
      description: "Conduct research on machine learning and AI algorithms.",
      jobPostingUrl: "https://example.com/job/20",
      jobPostingDate: "2025-01-20",
      status: "Offered",
    },
    {
      id: 21,
      title: "IT Support Specialist",
      company: "SupportHub",
      company_id: 121,
      location: "Washington, DC",
      salary: 80000,
      description: "Provide technical support to end-users and solve issues.",
      jobPostingUrl: "https://example.com/job/21",
      jobPostingDate: "2025-01-21",
      status: "Interviewing",
    },
    {
      id: 22,
      title: "Web Developer",
      company: "Webify",
      company_id: 122,
      location: "New York, NY",
      salary: 95000,
      description: "Design and build responsive websites using HTML, CSS, and JavaScript.",
      jobPostingUrl: "https://example.com/job/22",
      jobPostingDate: "2025-01-22",
      status: "Applied",
    },
    {
      id: 23,
      title: "QA Engineer",
      company: "TestWorks",
      company_id: 123,
      location: "Chicago, IL",
      salary: 105000,
      description: "Test software for bugs and ensure quality standards.",
      jobPostingUrl: "https://example.com/job/23",
      jobPostingDate: "2025-01-23",
      status: "Applied",
    }
  ];
  